use serde::Deserialize;

use crate::triage::{TriageVerdict, VerdictState};

/// The canonical AI-generated-during-triage disclaimer bellows
/// prepends to every comment posted as part of an applied verdict.
/// Matches the disclaimer the manual `/triage` skill uses so the two
/// produce visually identical comments on the issue.
pub const TRIAGE_AI_DISCLAIMER: &str = "> *This was generated by AI during triage.*";

/// Issue #87: cap below which we hand a comment body off to the
/// GitHub API. The hard API limit is 65536 characters; we clip well
/// short of that to leave headroom for any encoding / HTML / details-
/// tag wrapping the API might apply server-side. Bodies that would
/// exceed this cap are clipped by `truncate_for_github_comment` with
/// a footer pointing the operator at `bellows.log` for the full
/// output.
pub const GITHUB_COMMENT_MAX_CHARS: usize = 60_000;

/// Truncation footer appended by `truncate_for_github_comment` when
/// the input exceeds `GITHUB_COMMENT_MAX_CHARS`. The leading triple-
/// backtick line closes whichever code fence the run-log body's
/// `### Agent output tail` / `### \`cargo …\` output` block likely
/// left open (those code blocks carry the bulk of the byte weight,
/// so the truncation point is in practice almost always inside one
/// of them). The italicised text is the operator-visible marker —
/// `bellows.log` is the host-side file the truncated content lives
/// in. The trailing `</details>` re-closes the wrapping HTML element
/// that `build_log_body` emits so the rendered comment stays
/// well-formed.
const COMMENT_TRUNCATION_FOOTER: &str =
    "\n```\n\n_(truncated; full output in bellows.log on the operator's host)_\n\n</details>";

/// Bound `body` at `GITHUB_COMMENT_MAX_CHARS`, appending a truncation
/// footer when the input exceeds the cap. Bodies already within the
/// limit pass through unchanged.
///
/// Issue #87: large agent runs (huge stderr tails, multi-thousand-line
/// cargo output) produce run-log comment bodies above GitHub's 64 KiB
/// hard limit on issue/PR comment bodies. Posting such a body returns
/// HTTP 422 which historically collapsed the whole `finalise` step and
/// stranded the source issue at `agent-in-progress`. This helper is
/// the single source of truth for the cap — `runner::build_log_body`
/// calls it before returning, and `tracker::finalise` calls it
/// defensively on its `log_body` argument so the API-boundary contract
/// holds regardless of caller-side size-awareness.
pub fn truncate_for_github_comment(body: &str) -> String {
    if body.chars().count() <= GITHUB_COMMENT_MAX_CHARS {
        return body.to_string();
    }
    let footer_chars = COMMENT_TRUNCATION_FOOTER.chars().count();
    let keep_chars = GITHUB_COMMENT_MAX_CHARS.saturating_sub(footer_chars);
    let prefix: String = body.chars().take(keep_chars).collect();
    format!("{prefix}{COMMENT_TRUNCATION_FOOTER}")
}

/// All five canonical triage-state label strings — the set
/// `apply_verdict` strips off the issue's existing labels before
/// adding the new verdict's state label. Mirrors
/// `docs/agents/triage-labels.md`.
const CANONICAL_TRIAGE_LABELS: &[&str] = &[
    "needs-triage",
    "needs-info",
    "ready-for-agent",
    "ready-for-human",
    "wontfix",
];

#[derive(Debug, Clone, Deserialize)]
pub struct Issue {
    pub number: u64,
    pub title: String,
    #[serde(default)]
    pub labels: Vec<Label>,
    /// GitHub's `created_at` timestamp for the issue. Used by the
    /// multi-repo polling loop (issue #35) to break ties across repos
    /// — the oldest-by-created_at issue across all configured repos is
    /// claimed first. Optional in the deserializer so existing tests
    /// and any future caller that only cares about
    /// `number`/`title`/`labels` keep parsing minimal payloads; real
    /// GitHub responses always include the field.
    #[serde(default)]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
}

/// Read-only bundle of issue state the triage agent sees in
/// `/workspace/.bellows-triage-input.md`. Carries the issue body,
/// the title (so the agent doesn't have to infer from the body),
/// the current label set, and the first 100 ordered comments.
/// Order matters: a prior triage `needs-info` note may have asked a
/// question that a later reporter comment answers — the agent must
/// see the answer-after-the-question sequence to reach the right
/// verdict on re-triage. On very long issues (>100 comments) the
/// newest comments past the page-1 cap may not be visible to the
/// agent; see `fetch_issue_with_comments` for the rationale.
#[derive(Debug, Clone)]
pub struct IssueBundle {
    pub number: u64,
    pub title: String,
    pub body: Option<String>,
    pub labels: Vec<String>,
    pub comments: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct IssueWithBody {
    number: u64,
    title: String,
    #[serde(default)]
    body: Option<String>,
    #[serde(default)]
    labels: Vec<Label>,
}

#[derive(Debug, Deserialize)]
struct IssueComment {
    body: Option<String>,
}

#[derive(serde::Serialize)]
struct ListIssueCommentsParams {
    per_page: u32,
}

/// Fetch the issue body, labels, title, and the first 100 comments
/// for triage. Used by `bellows triage <N>` to build the in-container
/// input bundle. The container has no GitHub credentials — bellows
/// owns this fetch on the host side and writes the result to a
/// workspace file the agent reads.
///
/// Comments come back in API-default order (oldest-first on the
/// public GitHub API), which is the order a human reading the issue
/// would see them. The `per_page=100` cap (with no follow-up
/// pagination) matches the rest of bellows's GitHub-list calls; on
/// the rare issue with >100 comments the newest comments past page 1
/// will not be visible to the triage agent.
pub async fn fetch_issue_with_comments(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
) -> Result<IssueBundle, octocrab::Error> {
    let issue_route = format!("/repos/{owner}/{repo}/issues/{issue_number}");
    let issue: IssueWithBody = client.get(&issue_route, None::<&()>).await?;

    let comments_route = format!("/repos/{owner}/{repo}/issues/{issue_number}/comments");
    let comments_params = ListIssueCommentsParams { per_page: 100 };
    let comments: Vec<IssueComment> = client.get(&comments_route, Some(&comments_params)).await?;

    Ok(IssueBundle {
        number: issue.number,
        title: issue.title,
        body: issue.body,
        labels: issue.labels.into_iter().map(|l| l.name).collect(),
        comments: comments.into_iter().filter_map(|c| c.body).collect(),
    })
}

/// Apply a parsed-and-validated triage verdict to the GitHub issue.
/// Posts the AI-disclaimer-prefixed `comment_body`, posts the
/// `## Agent Brief` / `## Human Brief` payload as a separate comment
/// when relevant, and PATCHes the issue: replacing whichever
/// canonical triage label was on the issue with the new state's
/// label, and (for `wontfix`) also setting `state: closed`.
///
/// The PATCH is a single request that updates both labels and (when
/// closing) the issue's open/closed state — half-applied verdicts on
/// a transient network failure are easier to reason about when one
/// PATCH does the whole transition. Other labels on the issue (e.g.
/// `bug`, `enhancement`) are preserved.
///
/// The workspace-side wontfix-enhancement path (writing
/// `.out-of-scope/<filename>.md` to master) is handled by the caller
/// via `workspace::commit_to_branch` BEFORE invoking this function so
/// the closing comment can reference a file that already exists on
/// master.
pub async fn apply_verdict(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
    verdict: &TriageVerdict,
) -> Result<(), octocrab::Error> {
    // Step 1: read the issue's current labels so we can recompute the
    // new label set (drop any of the five canonical triage labels,
    // preserve everything else, add the verdict's state label).
    let issue_route = format!("/repos/{owner}/{repo}/issues/{issue_number}");
    let current: Issue = client.get(&issue_route, None::<&()>).await?;
    let mut new_labels: Vec<String> = current
        .labels
        .iter()
        .map(|l| l.name.clone())
        .filter(|n| !CANONICAL_TRIAGE_LABELS.contains(&n.as_str()))
        .collect();
    new_labels.push(verdict.state.label().to_string());
    new_labels.sort();
    new_labels.dedup();

    // Step 2: post the main verdict comment with the AI disclaimer.
    let comments_route = format!("/repos/{owner}/{repo}/issues/{issue_number}/comments");
    let main_body = format!("{}\n\n{}", TRIAGE_AI_DISCLAIMER, verdict.comment_body);
    let payload = serde_json::json!({ "body": main_body });
    let _: serde_json::Value = client.post(&comments_route, Some(&payload)).await?;

    // Step 3: when the verdict carries a separate brief (agent or
    // human), post it as its own comment so it can be located by
    // header (the downstream bellows-run pipeline scans for the
    // literal `## Agent Brief` header via fetch_agent_brief).
    let brief_comment_body = match verdict.state {
        VerdictState::ReadyForAgent => verdict
            .agent_brief
            .as_ref()
            .map(|b| format!("{}\n\n{}", TRIAGE_AI_DISCLAIMER, b)),
        VerdictState::ReadyForHuman => verdict
            .human_brief
            .as_ref()
            .map(|b| format!("{}\n\n{}", TRIAGE_AI_DISCLAIMER, b)),
        VerdictState::NeedsInfo | VerdictState::Wontfix => None,
    };
    if let Some(body) = brief_comment_body {
        let payload = serde_json::json!({ "body": body });
        let _: serde_json::Value = client.post(&comments_route, Some(&payload)).await?;
    }

    // Step 4: PATCH the issue. For wontfix verdicts, close the issue
    // in the same PATCH as the label swap so the GitHub-side state is
    // updated atomically (one request → consistent post-state).
    let mut patch = serde_json::Map::new();
    patch.insert("labels".into(), serde_json::json!(new_labels));
    if verdict.state == VerdictState::Wontfix {
        patch.insert("state".into(), serde_json::json!("closed"));
    }
    let _: serde_json::Value = client.patch(&issue_route, Some(&patch)).await?;

    Ok(())
}

#[derive(Debug, Clone, Deserialize)]
pub struct Label {
    pub name: String,
}

#[derive(Debug, thiserror::Error)]
pub enum ClaimError {
    #[error("issue was already claimed by another orchestrator")]
    Contended,
    #[error(transparent)]
    Octocrab(#[from] octocrab::Error),
}

#[derive(serde::Serialize)]
struct ListIssuesParams<'a> {
    labels: &'a str,
    state: &'a str,
}

/// Query params for the oldest-first `needs-triage` listing used by the
/// slice-T2 backlog drain (issue #22). Sibling of `ListIssuesParams`
/// — separate struct because `sort` / `direction` only apply when the
/// caller cares about ordering, and the existing `find_next_issue`
/// path explicitly does not (its tiebreak is "first un-claimed in
/// API-default order", and surfacing GitHub's sort/direction defaults
/// on every list call would be churn).
#[derive(serde::Serialize)]
struct ListNeedsTriageParams<'a> {
    labels: &'a str,
    state: &'a str,
    sort: &'a str,
    direction: &'a str,
}

/// List every open issue carrying `needs_triage_label`, ordered
/// oldest-first. Used by slice T2 (`bellows triage` with no issue
/// argument) to walk the `needs-triage` backlog serially through T1's
/// per-issue triage path.
///
/// Oldest-first is part of the contract — workspace state flows
/// between issues, and an older issue's verdict may set a precedent
/// (e.g. `wontfix` writing to `.out-of-scope/`) that a
/// later issue's triage should see. Walking newest-first would invert
/// that "earlier issues set precedent" intuition.
pub async fn list_needs_triage_issues(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    needs_triage_label: &str,
) -> Result<Vec<Issue>, octocrab::Error> {
    let params = ListNeedsTriageParams {
        labels: needs_triage_label,
        state: "open",
        sort: "created",
        direction: "asc",
    };
    let route = format!("/repos/{owner}/{repo}/issues");
    let issues: Vec<Issue> = client.get(&route, Some(&params)).await?;
    Ok(issues)
}

/// List the open issues carrying `pickup_label` and return the
/// lowest-`number` candidate that is neither already in progress nor
/// labelled `blocked_by_label`.
///
/// Issue #116 / ADR-0007: the polling-loop's normal pass filters out
/// issues carrying `blocked_by_label`; the re-loop sweep (run only
/// when this returns `None` and at least one blocked-by issue
/// exists) is the path that reconciles those dependents. Sorting
/// here is by `issue.number` ascending so each repo contributes its
/// lowest-number un-claimed unblocked candidate to the multi-repo
/// pick; the runner sorts the collected per-repo candidates again
/// (number → created_at → declared repo order) before picking.
pub async fn find_next_issue(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    pickup_label: &str,
    in_progress_label: &str,
    blocked_by_label: &str,
) -> Result<Option<Issue>, octocrab::Error> {
    let params = ListIssuesParams {
        labels: pickup_label,
        state: "open",
    };
    let route = format!("/repos/{owner}/{repo}/issues");
    let mut issues: Vec<Issue> = client.get(&route, Some(&params)).await?;
    // Sort ascending by issue.number so the lowest-number un-filtered
    // candidate wins. GitHub's default list ordering is newest-first
    // (created_at desc), which is fine on its own — but we need a
    // deterministic per-repo "lowest number" so the runner's cross-
    // repo tie-break has a stable per-repo seed to compare.
    issues.sort_by_key(|i| i.number);
    Ok(issues.into_iter().find(|issue| {
        let labels = &issue.labels;
        !labels.iter().any(|l| l.name == in_progress_label)
            && !labels.iter().any(|l| l.name == blocked_by_label)
    }))
}

/// List every open issue carrying `blocked_by_label` (the dependents
/// the re-loop sweep needs to reconcile). Returns the issues
/// verbatim so the sweep can fetch each brief and check each named
/// blocker's state.
///
/// Issue #116 / ADR-0007: separate call from `find_next_issue` so
/// the normal pass doesn't pay for the dependent list when there's
/// claimable work waiting — re-loop is the cold path.
pub async fn list_blocked_by_issues(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    pickup_label: &str,
    blocked_by_label: &str,
) -> Result<Vec<Issue>, octocrab::Error> {
    // GitHub's list-issues endpoint AND-s comma-separated labels
    // server-side, so we get the intersection of `pickup_label` and
    // `blocked_by_label` in one call.
    let combined = format!("{pickup_label},{blocked_by_label}");
    let params = ListIssuesParams {
        labels: &combined,
        state: "open",
    };
    let route = format!("/repos/{owner}/{repo}/issues");
    let issues: Vec<Issue> = client.get(&route, Some(&params)).await?;
    Ok(issues)
}

/// Minimal shape used by the re-loop sweep when checking a
/// blocker's state. We only care about `state`; the rest of the
/// payload is ignored.
#[derive(Debug, Deserialize)]
struct IssueState {
    state: String,
}

/// Query a single issue's open/closed state. Used by the re-loop
/// sweep (issue #116 / ADR-0007): the dependent's `blocked-by` label
/// is stripped iff every blocker named in its brief returns
/// `"closed"` here (any closure reason — merged PR, manual, wontfix
/// — counts; see ADR-0007).
pub async fn fetch_issue_state(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
) -> Result<IssueClosureState, octocrab::Error> {
    let route = format!("/repos/{owner}/{repo}/issues/{issue_number}");
    let issue: IssueState = client.get(&route, None::<&()>).await?;
    Ok(match issue.state.as_str() {
        "closed" => IssueClosureState::Closed,
        _ => IssueClosureState::Open,
    })
}

/// GitHub issue closure state. Only two variants because the re-loop
/// sweep's "is the blocker cleared?" question is binary; the per-
/// closure-reason distinction (merged vs wontfix vs manual) is
/// deliberately not exposed — see ADR-0007's "trust the operator
/// intent" rationale.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IssueClosureState {
    Open,
    Closed,
}

/// Strip `label` from `issue_number`'s label set. GET-then-PATCH
/// shape mirrors `claim` / `finalise` so the existing labels are
/// preserved minus the named label. Returns the updated issue.
///
/// Issue #116 / ADR-0007: the re-loop sweep calls this on each
/// dependent whose blockers have all closed; the cleared dependent
/// becomes claimable on the next polling tick's normal pass.
pub async fn strip_issue_label(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
    label: &str,
) -> Result<Issue, octocrab::Error> {
    let route = format!("/repos/{owner}/{repo}/issues/{issue_number}");
    let current: Issue = client.get(&route, None::<&()>).await?;
    let mut new_labels: Vec<String> = current
        .labels
        .iter()
        .map(|l| l.name.clone())
        .filter(|n| n != label)
        .collect();
    new_labels.sort();
    let body = serde_json::json!({ "labels": new_labels });
    let updated: Issue = client.patch(&route, Some(&body)).await?;
    Ok(updated)
}

/// Minimal shape of an open PR for the pre-claim check (#42). We only
/// care about the PR number (for the block-set log line) and the head
/// ref's name (to filter to bellows-authored `agent/*` branches).
#[derive(Debug, Deserialize)]
struct PullRequest {
    number: u64,
    head: PullRequestRef,
}

#[derive(Debug, Deserialize)]
struct PullRequestRef {
    #[serde(rename = "ref")]
    ref_name: String,
}

#[derive(serde::Serialize)]
struct ListPullsParams<'a> {
    state: &'a str,
    per_page: u32,
}

/// List the numbers of open PRs whose head ref starts with `agent/`
/// (the bellows branch-naming convention enforced by `agent_branch_name`).
///
/// Used by `run_once`'s pre-claim PR check (#42): when any such PR is
/// open, the polling tick must refuse to claim the next issue because
/// the prior PR may still gate master. The strict `agent/` prefix is
/// intentional — human-authored PRs on non-`agent/*` branches must not
/// stall bellows.
///
/// The GitHub list-pulls endpoint doesn't accept a head-prefix filter
/// server-side, so we paginate (well — request `per_page=100`, matching
/// the rest of bellows's GitHub-list calls; in practice bellows-on-bellows
/// has 0 or 1 open agent PRs at a time) and filter client-side.
pub async fn list_open_agent_prs(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
) -> Result<Vec<u64>, octocrab::Error> {
    let route = format!("/repos/{owner}/{repo}/pulls");
    let params = ListPullsParams {
        state: "open",
        per_page: 100,
    };
    let prs: Vec<PullRequest> = client.get(&route, Some(&params)).await?;
    Ok(prs
        .into_iter()
        .filter(|p| p.head.ref_name.starts_with("agent/"))
        .map(|p| p.number)
        .collect())
}

/// Single entry returned by the GitHub `git/matching-refs/{ref}` API. We
/// only care about the fully-qualified ref name (`refs/heads/agent/16-foo`);
/// the SHA + object metadata that GitHub also includes are ignored.
#[derive(Debug, Deserialize)]
struct MatchingRef {
    #[serde(rename = "ref")]
    ref_name: String,
}

/// Error from the pre-claim stale-branch sweep (#76 / ADR-0003). The
/// brief's exemplar signature returns `octocrab::Error` flat, but the
/// runner needs the failing branch name to populate
/// `RunOutcome::Blocked`'s reason — `octocrab::Error` doesn't preserve
/// the request URL through its Display impl, so we wrap with the
/// branch name (and `source` for the underlying API failure that
/// `run_once` formats for the block-reason `error` field).
#[derive(Debug, thiserror::Error)]
pub enum DeleteStaleBranchError {
    /// `GET .../git/matching-refs/heads/agent/{N}-` itself failed.
    /// `branch` is the anchored-prefix pattern in this case so the
    /// renderer still has a meaningful identifier to surface.
    #[error("listing stale agent branches for issue #{issue_number}: {source}")]
    ListFailed {
        issue_number: u64,
        #[source]
        source: octocrab::Error,
    },
    /// One specific `DELETE .../git/refs/heads/<branch>` failed. The
    /// surrounding sweep stops on the first failure so the runner can
    /// return Blocked and retry next tick.
    #[error("deleting stale agent branch `{branch}`: {source}")]
    DeleteFailed {
        branch: String,
        #[source]
        source: octocrab::Error,
    },
}

/// Pre-claim sweep (#76 / ADR-0003): delete every `agent/<issue_number>-*`
/// ref on origin so a stale branch from a prior failed run can't crash
/// the next reclaim with a non-fast-forward push. Lists matching refs
/// via `GET /repos/{owner}/{repo}/git/matching-refs/heads/agent/{N}-`
/// (the trailing dash is the anchored prefix that prevents
/// `agent/16-*` from matching `agent/160-*`), then issues
/// `DELETE /repos/{owner}/{repo}/git/refs/heads/{ref}` for each match.
///
/// Returns the short ref names (`agent/16-foo`, not the
/// `refs/heads/...`-prefixed form) that the sweep considered
/// successfully deleted. A 404 on an individual DELETE is folded into
/// the success set: the branch raced out from under us, same end
/// state. Any other non-success status (403 from branch protection or
/// PAT scope, 5xx, network failure) surfaces as
/// `DeleteStaleBranchError::DeleteFailed { branch, source }` so the
/// runner can return `RunOutcome::Blocked` carrying the failing
/// branch name; subsequent ticks retry, which is safe because the
/// operation is idempotent.
pub async fn delete_stale_agent_branches(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
) -> Result<Vec<String>, DeleteStaleBranchError> {
    let list_route = format!(
        "/repos/{owner}/{repo}/git/matching-refs/heads/agent/{issue_number}-",
    );
    let refs: Vec<MatchingRef> =
        client
            .get(&list_route, None::<&()>)
            .await
            .map_err(|source| DeleteStaleBranchError::ListFailed {
                issue_number,
                source,
            })?;

    let mut deleted = Vec::with_capacity(refs.len());
    for r in refs {
        // GitHub returns the fully-qualified `refs/heads/agent/16-foo`;
        // strip the `refs/heads/` prefix so the DELETE URL and the
        // returned name both use the short branch form bellows uses
        // everywhere else.
        let short = r
            .ref_name
            .strip_prefix("refs/heads/")
            .unwrap_or(&r.ref_name)
            .to_string();
        let delete_route = format!("/repos/{owner}/{repo}/git/refs/heads/{short}");
        let response = client
            ._delete(delete_route, None::<&()>)
            .await
            .map_err(|source| DeleteStaleBranchError::DeleteFailed {
                branch: short.clone(),
                source,
            })?;
        let status = response.status();
        if status.is_success() || status.as_u16() == 404 {
            deleted.push(short);
            continue;
        }
        // Non-404 failure: feed the raw response through octocrab's
        // standard error-mapping so the runner sees the same
        // `octocrab::Error::GitHub` shape any other API call would
        // produce (status code preserved, message parsed from the
        // body), and tag it with the branch name so the block-reason
        // can identify exactly which ref refused.
        let source = octocrab::map_github_error(response)
            .await
            .expect_err("non-success status must map to an Err");
        return Err(DeleteStaleBranchError::DeleteFailed {
            branch: short,
            source,
        });
    }
    Ok(deleted)
}

#[derive(Debug, Deserialize)]
struct Comment {
    body: Option<String>,
}

#[derive(serde::Serialize)]
struct ListCommentsParams {
    per_page: u32,
}

/// Parsed shape of the `**Blocked by:**` line in an agent brief.
/// The polling-loop re-loop sweep (ADR-0007) branches on this variant
/// when deciding whether to strip the `blocked-by` label.
///
/// - `NoBlockers`: the brief is present and either explicitly says
///   `None` (with or without a verbose annotation), has no
///   `**Blocked by:**` line at all, or only carries unparseable /
///   cross-repo references that the v1 parser cannot verify.
/// - `Blockers(nums)`: the brief lists one or more parseable
///   same-repo `#N` references. The re-loop checks each `N`'s state
///   and strips the label only when every one is `CLOSED`.
/// - `Unverifiable`: the input is not an agent brief at all (the
///   `## Agent Brief` header is absent). The caller leaves the
///   `blocked-by` label in place and logs a warning naming the
///   issue.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlockedBySection {
    NoBlockers,
    Blockers(Vec<u64>),
    Unverifiable,
}

/// Parse the `**Blocked by:**` line out of an agent brief body.
///
/// Cases handled (ADR-0007 / brief #116):
/// - `**Blocked by:** #95` → `Blockers([95])`
/// - `**Blocked by:** #95, #96` → `Blockers([95, 96])`
/// - `**Blocked by:** #95 (rationale)` → `Blockers([95])`
/// - `**Blocked by:** None` → `NoBlockers`
/// - `**Blocked by:** None — verbose tail` → `NoBlockers`
/// - missing `**Blocked by:**` line → `NoBlockers`
/// - cross-repo `owner/name#N` → ignored (logged via stderr); when
///   no parseable same-repo tokens remain → `NoBlockers`
/// - malformed `#NaN`, bare `abc`, `#` → ignored; when nothing
///   parseable remains → `NoBlockers`
/// - missing `## Agent Brief` header entirely → `Unverifiable`
pub fn parse_blocked_by_section(brief_body: &str) -> BlockedBySection {
    if !brief_body.contains("## Agent Brief") {
        return BlockedBySection::Unverifiable;
    }

    // Find the line beginning with `**Blocked by:**` (case-sensitive
    // — this is the shape `/triage` emits). Anywhere on a line so
    // leading whitespace / list-bullets don't break the match.
    let prefix = "**Blocked by:**";
    let Some(line) = brief_body.lines().find_map(|l| {
        let trimmed = l.trim_start();
        trimmed.strip_prefix(prefix).map(|rest| rest.trim())
    }) else {
        return BlockedBySection::NoBlockers;
    };

    // Drop any trailing parenthetical annotation (`#95 (rationale)`
    // → `#95`). We only need to strip a single trailing `(...)` —
    // the line shape is "one or more refs, optionally followed by a
    // human-readable note in parens".
    let body = match line.find('(') {
        Some(idx) => line[..idx].trim(),
        None => line,
    };

    // Explicit `None` (with or without a verbose annotation) clears
    // any blockers. We check this BEFORE the comma-split so
    // "None — can start immediately" matches even though the
    // em-dash tail isn't a token.
    let body_lower = body.to_ascii_lowercase();
    if body_lower == "none"
        || body_lower.starts_with("none ")
        || body_lower.starts_with("none\t")
        || body_lower.starts_with("none.")
        || body_lower.starts_with("none,")
        || body_lower.starts_with("none—")
        || body_lower.starts_with("none–")
        || body_lower.starts_with("none-")
    {
        return BlockedBySection::NoBlockers;
    }

    // Split on commas; each token must be `#N` where N parses as
    // u64. Cross-repo `owner/name#N` and bare malformed tokens are
    // logged to stderr and dropped from the result.
    let mut blockers = Vec::new();
    for raw in body.split(',') {
        let token = raw.trim();
        if token.is_empty() {
            continue;
        }
        if token.contains('/') {
            eprintln!(
                "bellows: ignoring cross-repo blocker reference `{}` in **Blocked by:** line (v1 is same-repo only; see ADR-0007)",
                token,
            );
            continue;
        }
        let Some(num_str) = token.strip_prefix('#') else {
            eprintln!(
                "bellows: ignoring malformed blocker token `{}` in **Blocked by:** line (expected `#N`)",
                token,
            );
            continue;
        };
        match num_str.parse::<u64>() {
            Ok(n) => blockers.push(n),
            Err(_) => {
                eprintln!(
                    "bellows: ignoring malformed blocker token `#{}` in **Blocked by:** line (not a u64)",
                    num_str,
                );
            }
        }
    }

    if blockers.is_empty() {
        BlockedBySection::NoBlockers
    } else {
        BlockedBySection::Blockers(blockers)
    }
}

/// Look up the latest agent-brief comment on an issue (the one whose body
/// includes the `## Agent Brief` header that `/triage` posts). Returns
/// `Ok(None)` if no such comment exists.
pub async fn fetch_agent_brief(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
) -> Result<Option<String>, octocrab::Error> {
    let route = format!("/repos/{owner}/{repo}/issues/{issue_number}/comments");
    let params = ListCommentsParams { per_page: 100 };
    let comments: Vec<Comment> = client.get(&route, Some(&params)).await?;

    Ok(comments
        .into_iter()
        .filter_map(|c| c.body)
        .rfind(|b| b.contains("## Agent Brief")))
}

/// Inputs for `finalise`. Bundled into a struct rather than passed as
/// 8 positional arguments — clippy's too_many_arguments threshold and
/// readability both improve.
pub struct FinaliseRequest<'a> {
    pub owner: &'a str,
    pub repo: &'a str,
    pub issue_number: u64,
    pub pr_number: u64,
    pub in_progress_label: &'a str,
    pub outcome_label: &'a str,
    pub log_body: &'a str,
}

/// Result of `finalise`. Carries the post-transition issue plus a flag
/// indicating whether the in-progress label was already gone before
/// finalise ran — the slice-10 `bellows kill <N>` operator path: when
/// the operator transitioned the label out from under the running
/// orchestrator, finalise still posts the log comment so the
/// abandoned-mid-run state is recorded, but skips the PATCH (the
/// operator's label is already correct) and signals back so run_once
/// can return `RunOutcome::Cancelled` instead of `RunOutcome::Finalised`.
///
/// `comment_post_failure` (issue #87) carries the formatted API error
/// when the run-log comment POST itself failed — typically a 422
/// because the body exceeds GitHub's 64 KiB hard limit, but also any
/// transient 5xx / network blip on the comments endpoint. The label
/// transition runs BEFORE the comment post, so this field being `Some`
/// means the state machine reached its terminal label correctly and
/// only the observability comment is missing; the caller surfaces this
/// as an operator-visible log warning rather than treating it as a
/// pipeline-fatal error.
pub struct FinaliseOutcome {
    pub issue: Issue,
    pub externally_cancelled: bool,
    pub comment_post_failure: Option<String>,
}

/// Lightweight GET on an issue's current labels to check whether
/// `in_progress_label` is still present. Used by `run_once` BEFORE
/// opening the PR to detect mid-run cancellation by `bellows kill <N>`
/// (slice 10) — without this check, the cancellation is only detected
/// in `finalise`, which is too late: the PR has already been opened
/// (potentially as ready-for-review with a "Success" log header) and
/// post_pr_comment has already posted the findings comment.
///
/// Returns `Ok(true)` if the in-progress label is still on the issue,
/// `Ok(false)` if it's been removed externally (operator cancelled).
/// Errors propagate as-is — the runner treats fetch failures as
/// "assume still in progress" (best-effort, doesn't block the pipeline).
pub async fn issue_in_progress(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
    in_progress_label: &str,
) -> Result<bool, octocrab::Error> {
    let route = format!("/repos/{owner}/{repo}/issues/{issue_number}");
    let current: Issue = client.get(&route, None::<&()>).await?;
    Ok(current.labels.iter().any(|l| l.name == in_progress_label))
}

/// Transition the issue's labels from `in_progress_label` to
/// `outcome_label`, then post the run-log comment on the PR. Generic
/// over the outcome — the caller decides whether the run was a success
/// (`agent-done`), a failure (`agent-failed`), or one of the more
/// specific failure kinds added in later slices.
///
/// **Step order matters (issue #87).** The label PATCH runs BEFORE the
/// comment POST so the issue's state machine reaches its terminal
/// label even if the comment endpoint fails — historically the order
/// was reversed and a 422 on the comment (body exceeds GitHub's 64 KiB
/// hard limit) left the source issue stuck at `agent-in-progress`,
/// blocking the polling loop on the open `agent/*` PR. With this
/// ordering the comment post is observability-only: a failure is
/// surfaced via `FinaliseOutcome::comment_post_failure` (so the
/// caller can write a log warning) but does NOT propagate as `Err`
/// to `run_once`. Any subsequent post-label failure (transient 5xx,
/// network blip, rate limit on the comments endpoint) is handled the
/// same way.
///
/// If the GET shows that `in_progress_label` is no longer on the issue
/// (the slice-10 `bellows kill <N>` operator path), the comment is still
/// attempted but the label PATCH is skipped — the operator's manual
/// transition has already moved the issue to the cancelled state, and a
/// second PATCH would clobber that.
pub async fn finalise(
    client: &octocrab::Octocrab,
    req: FinaliseRequest<'_>,
) -> Result<FinaliseOutcome, octocrab::Error> {
    let issue_route = format!(
        "/repos/{owner}/{repo}/issues/{issue_number}",
        owner = req.owner,
        repo = req.repo,
        issue_number = req.issue_number,
    );
    let current: Issue = client.get(&issue_route, None::<&()>).await?;

    let externally_cancelled = !current.labels.iter().any(|l| l.name == req.in_progress_label);
    let issue_after_patch = if externally_cancelled {
        current
    } else {
        let mut new_labels: Vec<String> = current
            .labels
            .iter()
            .map(|l| l.name.clone())
            .filter(|n| n != req.in_progress_label)
            .collect();
        new_labels.push(req.outcome_label.to_string());
        new_labels.sort();

        let body = serde_json::json!({ "labels": new_labels });
        client.patch(&issue_route, Some(&body)).await?
    };

    // Comment POST is observability-only — a failure here (e.g. 422
    // body-too-long, transient 5xx) must NOT roll back the label
    // transition above or propagate as `Err` to the runner. Surface the
    // failure via `comment_post_failure` so the caller can log an
    // operator-visible warning instead.
    let comment_route = format!(
        "/repos/{owner}/{repo}/issues/{pr_number}/comments",
        owner = req.owner,
        repo = req.repo,
        pr_number = req.pr_number,
    );
    // Defensive cap (issue #87) — `runner::build_log_body` already
    // bounds the body, but `finalise` is the GitHub API boundary so we
    // re-apply the truncation here. The helper passes short bodies
    // through unchanged, so this is a no-op on the common path.
    let bounded_body = truncate_for_github_comment(req.log_body);
    let comment_body = serde_json::json!({ "body": bounded_body });
    let post_result: Result<serde_json::Value, octocrab::Error> =
        client.post(&comment_route, Some(&comment_body)).await;
    let comment_post_failure = post_result.err().map(|e| e.to_string());

    Ok(FinaliseOutcome {
        issue: issue_after_patch,
        externally_cancelled,
        comment_post_failure,
    })
}

/// GitHub-side handler for `bellows kill <N>`. Posts a short
/// AI-disclaimer-style cancellation comment so a human reading the
/// issue knows what happened, then transitions the issue's labels by
/// removing `from_label` (typically `agent-in-progress`) and adding
/// `to_label` (typically `agent-cancelled`). Sibling of `finalise` —
/// same comment-then-label-swap shape, but with a fixed comment body
/// rather than the runner's per-phase log summary.
pub async fn transition_to_cancelled(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
    from_label: &str,
    to_label: &str,
) -> Result<Issue, octocrab::Error> {
    let now = chrono::Utc::now();
    let comment_body = format!(
        "> *bellows: cancelled by operator at {}*",
        now.to_rfc3339(),
    );

    let comment_route = format!("/repos/{owner}/{repo}/issues/{issue_number}/comments");
    let payload = serde_json::json!({ "body": comment_body });
    let _: serde_json::Value = client.post(&comment_route, Some(&payload)).await?;

    let issue_route = format!("/repos/{owner}/{repo}/issues/{issue_number}");
    let current: Issue = client.get(&issue_route, None::<&()>).await?;

    let mut new_labels: Vec<String> = current
        .labels
        .iter()
        .map(|l| l.name.clone())
        .filter(|n| n != from_label)
        .collect();
    if !new_labels.iter().any(|n| n == to_label) {
        new_labels.push(to_label.to_string());
    }
    new_labels.sort();

    let body = serde_json::json!({ "labels": new_labels });
    let updated: Issue = client.patch(&issue_route, Some(&body)).await?;
    Ok(updated)
}

/// Post a freestanding comment on an issue or PR (PRs share the issues
/// comments endpoint on GitHub). Used by the runner to surface the
/// review-phase findings file as a `## Review findings` comment without
/// the label-swap baked into `finalise`.
pub async fn post_pr_comment(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    pr_number: u64,
    body: &str,
) -> Result<(), octocrab::Error> {
    let route = format!("/repos/{owner}/{repo}/issues/{pr_number}/comments");
    let payload = serde_json::json!({ "body": body });
    let _: serde_json::Value = client.post(&route, Some(&payload)).await?;
    Ok(())
}

/// Add labels to an issue or PR without replacing its existing label set.
/// Pull requests share GitHub's issue-labels API; the runner uses this
/// for ADR-0006 `agent-noted` PR labels so the auto-merge workflow can
/// observe the note gate on the PR object itself.
pub async fn add_issue_labels(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
    labels: &[&str],
) -> Result<Vec<Label>, octocrab::Error> {
    let route = format!("/repos/{owner}/{repo}/issues/{issue_number}/labels");
    let payload = serde_json::json!({ "labels": labels });
    client.post(&route, Some(&payload)).await
}

pub async fn claim(
    client: &octocrab::Octocrab,
    owner: &str,
    repo: &str,
    issue_number: u64,
    pickup_label: &str,
    in_progress_label: &str,
) -> Result<Issue, ClaimError> {
    let route = format!("/repos/{owner}/{repo}/issues/{issue_number}");

    let current: Issue = client.get(&route, None::<&()>).await?;
    if !current.labels.iter().any(|l| l.name == pickup_label) {
        return Err(ClaimError::Contended);
    }

    let mut new_labels: Vec<String> = current
        .labels
        .iter()
        .map(|l| l.name.clone())
        .filter(|n| n != pickup_label)
        .collect();
    new_labels.push(in_progress_label.to_string());
    new_labels.sort();

    let body = serde_json::json!({ "labels": new_labels });
    let updated: Issue = client.patch(&route, Some(&body)).await?;
    Ok(updated)
}
